noconnor/JUnitPerf

README.md, src/main/java/com/github/noconnor/junitperf/JUnitPerfRule.java, src/test/java/com/github/noconnor/junitperf/JUnitPerfRuleTest.java
Fixes #11 
- Making reporters a variable argument list
- Looping over all reporters to generate multiple reports
=> Adding suport for multiple report modules

README.md, build.gradle, src/main/java/com/github/noconnor/junitperf/JUnitPerfTest.java, src/main/java/com/github/noconnor/junitperf/JUnitPerfTestRequirement.java, src/main/java/com/github/noconnor/junitperf/data/EvaluationContext.java, src/test/examples/com/github/noconnor/junitperf/examples/ExampleFailureTests.java, src/test/java/com/github/noconnor/junitperf/JUnitPerfRuleTest.java, src/test/java/com/github/noconnor/junitperf/data/EvaluationContextTest.java, src/test/java/com/github/noconnor/junitperf/reporting/BaseReportGeneratorTest.java
Fixes #2 
- Renaming annotation fields
- Technically an interface change but only stepping minor version
=> Refactroing annotation interface

README.md, build.gradle, src/main/java/com/github/noconnor/junitperf/reporting/ReportGenerator.java, src/main/java/com/github/noconnor/junitperf/reporting/providers/ConsoleReportGenerator.java, src/main/java/com/github/noconnor/junitperf/reporting/providers/CsvReportGenerator.java, src/main/java/com/github/noconnor/junitperf/reporting/providers/HtmlReportGenerator.java, src/test/java/com/github/noconnor/junitperf/reporting/providers/ConsoleReportGeneratorTest.java, src/test/java/com/github/noconnor/junitperf/reporting/providers/CsvReportGeneratorTest.java, src/test/java/com/github/noconnor/junitperf/reporting/providers/HtmlReportGeneratorTest.java, src/test/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatementTest.java
Fixes #6 
- Adding unittests
- Minor update to README
- Adding getter method to reporter classes
=> Increasing code coverage

build.gradle, src/main/java/com/github/noconnor/junitperf/data/EvaluationContext.java, src/test/java/com/github/noconnor/junitperf/data/EvaluationContextTest.java
Fixes #3 
- Adding test annotation validation to ExecutionContext
=> Adding annotation attribute validation

README.md
Fixes #
- make it easier to copy code to include latest version, instead of having to look it up and replace text!
-
-
=> update README with instruction to retrieve latest version

README.md, src/main/java/com/github/noconnor/junitperf/data/EvaluationContext.java, src/test/examples/com/github/noconnor/junitperf/examples/ExampleSuccessTests.java, src/test/java/com/github/noconnor/junitperf/data/EvaluationContextTest.java
Fixes #19 
- Setting threshold validation booleans to correct value when no validation is run
=> Fixing issue #19 - no validation bug

build.gradle, src/main/resources/templates/report.twig, src/test/resources/html/example_all_failed_report.html, src/test/resources/html/example_all_passed_report.html, src/test/resources/html/example_mixed_report.html, src/test/resources/html/example_some_failures_report.html
Fixes #17 
- Minor update to base twig template
=> Modifying html template

src/main/resources/templates/report.twig, src/test/resources/html/example_all_failed_report.html, src/test/resources/html/example_all_passed_report.html, src/test/resources/html/example_mixed_report.html, src/test/resources/html/example_some_failures_report.html
- Making tooltip text more descriptive
=> Updating tooltip message on percentile graph

src/main/resources/templates/report.twig, src/test/resources/html/example_all_failed_report.html, src/test/resources/html/example_all_passed_report.html, src/test/resources/html/example_mixed_report.html, src/test/resources/html/example_some_failures_report.html
Fixes #22 
- Added CSV export link to percentile plots
=> Issue#22/allow exporting of percentile graph as csv

build.gradle, src/main/java/com/github/noconnor/junitperf/statistics/providers/DescriptiveStatisticsCalculator.java, src/test/java/com/github/noconnor/junitperf/statistics/providers/DescriptiveStatisticsCalculatorTest.java
Fixes #33 
- Adding default statistic values when execution count is 0
=> Fixing statistics reporting when evaluation count is 0

build.gradle, src/main/resources/templates/report.twig, src/test/resources/html/example_all_failed_report.html, src/test/resources/html/example_all_passed_report.html, src/test/resources/html/example_mixed_report.html, src/test/resources/html/example_some_failures_report.html
Fixes #35 
- Adding horizontal axis limits
=> Fixing horizontal axis scale

build.gradle
Fixes #
- No longer publish uber jar
=> Removing bundling of jar dependencies

build.gradle, src/main/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatement.java
Fixes #46 
- Change rate limit create method if rampup period is 0
=> Fixing bug in ratelimiter when rampUp period is 0

.travis.yml, junitperf-core/src/main/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatement.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/statistics/StatisticsCalculator.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/statistics/providers/DescriptiveStatisticsCalculator.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/statistics/providers/NoOpStatisticsCollector.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatementTest.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/statistics/providers/DescriptiveStatisticsCalculatorTest.java
Fixes #62 
- Update PerformanceEvaluationStatement to reset statistics calculator on each call to evaluation
=> Rest statistics if test statement is re-run

README.md
- New section for reports grouping in the README.
=> Adding documentation for reports grouping.

.github/workflows/publish.yml, pom.xml
- Adding git user config
- Fixing server id in parent pom
=> Fix for maven deploy

.github/workflows/publish.yml, pom.xml
=> Switching to release plugin

.github/workflows/publish.yml, junit4-examples/pom.xml, junit5-examples/pom.xml, junitperf-core/pom.xml, junitperf-junit4/pom.xml, junitperf-junit5/pom.xml, pom.xml
- Adding batch mode switch
- Updating snapshot version
=> Updating publish command

README.md
=> Template documentation added.

README.md, junit5-examples/src/test/java/com/github/noconnor/junitperf/examples/ExampleSuccessTests.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/JUnitPerfTest.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/data/EvaluationContext.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/statements/EvaluationTask.java, junitperf-core/src/main/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatement.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/data/EvaluationContextTest.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/reporting/BaseReportGeneratorTest.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/statements/EvaluationTaskTest.java, junitperf-core/src/test/java/com/github/noconnor/junitperf/statements/PerformanceEvaluationStatementTest.java
- Add new test configuration parameter totalExecutions
- Update core code to use totalExecutions 
- Updated documentation to explain new parameter usage
- Updated EvaluationContext to calculate test run time correctly
=> Support total executions limit

.github/workflows/publish.yml
Fixes Issue with push pipeline
- Specify master as target ref for checkout when building releases
=> Testing GitHub actions fix

junitperf-junit5/src/main/java/com/github/noconnor/junitperf/suite/SuiteRegistry.java, junitperf-junit5/src/test/java/com/github/noconnor/junitperf/suite/SuiteRegistryTest.java
Fixes nested suites issue
- when a suite of suites is being run, the perf configuration from the root suite will be used , nested suite settings will be ignored
=> Fix for suite of suites

.github/workflows/ci.yml, .github/workflows/publish.yml
Fixes nodejs warning
- Updating github actions
=> Updating actions

junitperf-core/src/main/resources/templates/report.template, junitperf-core/src/test/java/com/github/noconnor/junitperf/reporting/providers/HtmlReportGeneratorTest.java, junitperf-core/src/test/resources/html/example_aborted_failed_success.html, junitperf-core/src/test/resources/html/example_all_failed_report.html, junitperf-core/src/test/resources/html/example_all_passed_report.html, junitperf-core/src/test/resources/html/example_mixed_report.html, junitperf-core/src/test/resources/html/example_some_failures_report.html
Fixes #122 
- Added missing ';' to html template
=> Fix for html report rendering issue

.github/workflows/publish.yml, pom.xml
Fixes issue with maven publish
=> Updating maven gpg plugin
